/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VictoryRouteImport } from './routes/victory'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as FailureRouteImport } from './routes/failure'
import { Route as DoorRouteImport } from './routes/door'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzleIdRouteImport } from './routes/puzzle.$id'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'

const VictoryRoute = VictoryRouteImport.update({
  id: '/victory',
  path: '/victory',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const FailureRoute = FailureRouteImport.update({
  id: '/failure',
  path: '/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorRoute = DoorRouteImport.update({
  id: '/door',
  path: '/door',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleIdRoute = PuzzleIdRouteImport.update({
  id: '/puzzle/$id',
  path: '/puzzle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/door': typeof DoorRoute
  '/failure': typeof FailureRoute
  '/vault': typeof VaultRoute
  '/victory': typeof VictoryRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/puzzle/$id': typeof PuzzleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/door': typeof DoorRoute
  '/failure': typeof FailureRoute
  '/vault': typeof VaultRoute
  '/victory': typeof VictoryRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/puzzle/$id': typeof PuzzleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/door': typeof DoorRoute
  '/failure': typeof FailureRoute
  '/vault': typeof VaultRoute
  '/victory': typeof VictoryRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/puzzle/$id': typeof PuzzleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/door'
    | '/failure'
    | '/vault'
    | '/victory'
    | '/admin/sessions'
    | '/puzzle/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/door'
    | '/failure'
    | '/vault'
    | '/victory'
    | '/admin/sessions'
    | '/puzzle/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/door'
    | '/failure'
    | '/vault'
    | '/victory'
    | '/admin/sessions'
    | '/puzzle/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoorRoute: typeof DoorRoute
  FailureRoute: typeof FailureRoute
  VaultRoute: typeof VaultRoute
  VictoryRoute: typeof VictoryRoute
  PuzzleIdRoute: typeof PuzzleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/victory': {
      id: '/victory'
      path: '/victory'
      fullPath: '/victory'
      preLoaderRoute: typeof VictoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failure': {
      id: '/failure'
      path: '/failure'
      fullPath: '/failure'
      preLoaderRoute: typeof FailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/door': {
      id: '/door'
      path: '/door'
      fullPath: '/door'
      preLoaderRoute: typeof DoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$id': {
      id: '/puzzle/$id'
      path: '/puzzle/$id'
      fullPath: '/puzzle/$id'
      preLoaderRoute: typeof PuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSessionsRoute: typeof AdminSessionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSessionsRoute: AdminSessionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoorRoute: DoorRoute,
  FailureRoute: FailureRoute,
  VaultRoute: VaultRoute,
  VictoryRoute: VictoryRoute,
  PuzzleIdRoute: PuzzleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
